### ISSUE TITLE
Uknown function params_lookup

### ISSUE THREAD

**Issue by ghost** [ucbpi/puppet-ssl#6]
I get an error when trying to use this module. I have stdlibs 3.2.0. Are there any other modules this module depends on?

**Comment by arusso** [comment]
The module on the forge has an (albeit weak) dependency on arusso-oski. It may also work with example42-puppi.

 I think if you pass all the values to the define you can get around the need for installing either of those modules. In all cases I've experienced thus far, I've always passed parameters directly to the ssl::cert define, thus not really needing the params_lookup function calls.

The commit referenced above removes params_lookup calls in favor of hiera calls. This breaks 2.6 compatibility, so I'll make it's way into the 2.0.0 release.

**Comment by ghost** [comment]
It would be wise to mention that this is Hiera only module. Also nowhere does it state that there are other requirements besides stdlib module. Anyway, this module is too limiting.
